// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-BsRhJzVtD9nMPk7MkZLVzvH9o6vJsjE',
    appId: '1:798926575172:web:bd5e1f1163bf4843f00e11',
    messagingSenderId: '798926575172',
    projectId: 'user-crud-8f4e7',
    authDomain: 'user-crud-8f4e7.firebaseapp.com',
    storageBucket: 'user-crud-8f4e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIh19mnCSEW7fWTl5PRAvue5TE8hyLGrE',
    appId: '1:798926575172:android:8450046c4bca077df00e11',
    messagingSenderId: '798926575172',
    projectId: 'user-crud-8f4e7',
    storageBucket: 'user-crud-8f4e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXfOdEIA6urq4iGJDOOJwHg7F_Rb_U1B8',
    appId: '1:798926575172:ios:4fcf4da9ef9c4134f00e11',
    messagingSenderId: '798926575172',
    projectId: 'user-crud-8f4e7',
    storageBucket: 'user-crud-8f4e7.appspot.com',
    iosBundleId: 'com.example.userCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXfOdEIA6urq4iGJDOOJwHg7F_Rb_U1B8',
    appId: '1:798926575172:ios:4fcf4da9ef9c4134f00e11',
    messagingSenderId: '798926575172',
    projectId: 'user-crud-8f4e7',
    storageBucket: 'user-crud-8f4e7.appspot.com',
    iosBundleId: 'com.example.userCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-BsRhJzVtD9nMPk7MkZLVzvH9o6vJsjE',
    appId: '1:798926575172:web:a01ded4fa40d68cbf00e11',
    messagingSenderId: '798926575172',
    projectId: 'user-crud-8f4e7',
    authDomain: 'user-crud-8f4e7.firebaseapp.com',
    storageBucket: 'user-crud-8f4e7.appspot.com',
  );
}
